export const TEAM = {
    NJD : 'New Jersey Devils',
    NYI : 'New York Islanders',
    NYR : 'New York Rangers',
    MTL : 'Montreal Canadiens',
    OTT : 'Ottawa Senators',
    TOR : 'Toronto Maple Leafs',
    BOS : 'Boston Bruins',
    PHI : 'Philadelphia Flyers',
    PIT : 'Pittsburgh Penguins',
    BUF : 'Buffalo Sabres',
    CAR : 'Carolina Hurricanes',
    FLA : 'Florida Panthers',
    TBL : 'Tampa Bay Lightning',
    WSH : 'Washington Capitals',
    CHI : 'Chicago Blackhawks',
    DET : 'Detroit Red Wings',
    NSH : 'Nashville Predators',
    STL : 'St. Louis Blues',
    CGY : 'Calgary Flames',
    COL : 'Colorado Avalanche',
    EDM : 'Edmonton Oilers',
    VAN : 'Vancouver Canucks',
    ANA : 'Anaheim Ducks',
    DAL : 'Dallas Stars',
    LAK : 'Los Angeles Kings',
    SJS : 'San Jose Sharks',
    CBJ : 'Columbus Blue Jackets',
    MIN : 'Minnesota Wild',
    WIN : 'Winnipeg Jets',
    ARI : 'Arizona Coyotes',
    VGK : 'Vegas Golden Knights',
}

export const TEAM_SHORT_NAMES = {
    NJD : 'Devils',
    NYI : 'Islanders',
    NYR : 'Rangers',
    MTL : 'Canadiens',
    OTT : 'Senators',
    TOR : 'Leafs',
    BOS : 'Bruins',
    PHI : 'Flyers',
    PIT : 'Penguins',
    BUF : 'Sabres',
    CAR : 'Hurricannes',
    FLA : 'Panthers',
    TBL : 'Lighting',
    WSH : 'Capitals',
    CHI : 'Blackhawks',
    DET : 'Red Wings',
    NSH : 'Predators',
    STL : 'Blues',
    CGY : 'Flames',
    COL : 'Avalanche',
    EDM : 'Oilers',
    VAN : 'Canucks',
    ANA : 'Ducks',
    DAL : 'Stars',
    LAK : 'Kings',
    SJS : 'Sharks',
    CBJ : 'Blue Jackets',
    MIN : 'Wild',
    WIN : 'Jets',
    ARI : 'Coyotes',
    VGK : 'Golden Knights',
}


export const Teams = new Map<string, string>([
    ['NJD', TEAM.NJD],
    ['NYI', TEAM.NYI],
    ['NYR', TEAM.NYR],
    ['MTL', TEAM.MTL],
    ['OTT', TEAM.OTT],
    ['TOR', TEAM.TOR],
    ['BOS', TEAM.BOS],
    ['PHI', TEAM.PHI],
    ['PIT', TEAM.PIT],
    ['BUF', TEAM.BUF],
    ['CAR', TEAM.CAR],
    ['FLA', TEAM.FLA],
    ['TBL', TEAM.TBL],
    ['WSH', TEAM.WSH],
    ['CHI', TEAM.CHI],
    ['DET', TEAM.DET],
    ['NSH', TEAM.NSH],
    ['STL', TEAM.STL],
    ['CGY', TEAM.CGY],
    ['COL', TEAM.COL],
    ['EDM', TEAM.EDM],
    ['VAN', TEAM.VAN],
    ['ANA', TEAM.ANA],
    ['DAL', TEAM.DAL],
    ['LAK', TEAM.LAK],
    ['SJS', TEAM.SJS],
    ['CBJ', TEAM.CBJ],
    ['MIN', TEAM.MIN],
    ['WIN', TEAM.WIN],
    ['ARI', TEAM.ARI],
    ['VGK', TEAM.VGK],
]);